# Copyright 2018 Google Inc. All rights reserved.
# Use of this source code is governed by the Apache 2.0
# license that can be found in the LICENSE file.
runtime: go113
instance_class: F1
service: dea-wms

handlers:
# Configure App Engine to serve any static assets.
- url: /map
  static_dir: static

# Use HTTPS for all requests.
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

# Limit cost and study performance
automatic_scaling:
  max_instances: 2
  max_concurrent_requests: 16
  min_pending_latency: 2000ms
